---
- name: Create users
  hosts: all
  become: yes

  vars_files:
    - users.yml # You must replace the file

#The file must be same as:
#users:
#  - name: 'TestAcc01' 
#    pass: 'Test01!' 
#    grp: 'sudo'


  tasks:
    - name: "Create more users"
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.pass | password_hash('sha512') }}"
        groups: "{{ item.grp}}"
        state: present
        shell: /bin/bash
      loop: "{{ users }}"

    - name: "Add ll allias"
      ansible.builtin.lineinfile:
        path: "/home/{{ item.name }}/.bashrc"
        line: "alias ll='ls -la'"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        create: yes
        mode: '0644'
      loop: "{{ users }}"


    - name: "Add l allias"
      ansible.builtin.lineinfile:
        path: "/home/{{ item.name }}/.bashrc"
        line: "alias l='ls'"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        create: yes
        mode: '0644'
      loop: "{{ users }}"