---
- name: Create user
  hosts: all
  become: yes

  vars:
    username: Istics
    password: Test123!

  tasks:
    - name: "Create user"
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        shell: /bin/bash 
        groups: sudo
        append: yes
        password: "{{ password | password_hash('sha512') }}"


    - name: "Add alias"
      ansible.builtin.lineinfile:
        path: "/home/{{ username }}/.bashrc"
        line: "{{ item }}"
      loop:
        - "alias ll='ls -la'"
        - "alias l='ls'"